### ISSUE TITLE
（希望）关于语音和礼物

### ISSUE THREAD

**Issue by Zawinzala** [hling51325/bilibili-live-danmaku#19]
语音感谢做都做了，（干脆语音读出弹幕 （语速调整-+

![image](https://user-images.githubusercontent.com/24386549/126667725-a4652368-1731-4546-b811-9672fa27d9f1.png)
重复的礼物希望能合并一下（

**Comment by usagiring** [comment]
可以的， 其实最早就想做回复弹幕的（包括入场信息等），只是我还没想好怎么设计UI，不想加太多操作框，又能让表意区分开，，所以就先试试礼物，今后会把这些都加上，还想加个自定义文本让系统读的小工具。

辣条这个是bug，上次B站礼物改版之后就这样了，我来修修。

**Comment by Zawinzala** [comment]
好！！！期待！

**Comment by Zawinzala** [comment]
![屏幕截图 2021-08-04 041737](https://user-images.githubusercontent.com/24386549/128084807-cb71dc09-affb-48fd-af4e-0db56fa73388.png)

**Comment by usagiring** [comment]
有心了，多谢！我会作为参考

**Comment by Zawinzala** [comment]
哈哈哈哈，看到了。好强啊， 评论和超级聊天有什么区别？ {comment.content} {superchat.content}

**Comment by usagiring** [comment]
{comment.content} 是弹幕的内容
 {superchat.content} 是醒目留言的内容
嗯嗯，这里还是需要补一个示例说明，不然不好理解

**Comment by Zawinzala** [comment]
更新了，帅
