### ISSUE TITLE
打开软件之后一直卡在loading加载的页面

### ISSUE THREAD

**Issue by Mintonmu** [hling51325/bilibili-live-danmaku#21]
![image](https://user-images.githubusercontent.com/28354069/138050959-02bc815d-5da6-4074-91e6-3630bf31c921.png)

**Comment by usagiring** [comment]
试试打开应用情况下请求
http://127.0.0.1:8081/api/touch
http://localhost:8081/api/touch

安装目录下powershell执行命令，进debug，是否能启动有无错误日志
 ./bilibili-danmaku.exe --remote-debugging-port=8315

**Comment by Mintonmu** [comment]
我今天又重新安装了一遍，然后就离奇的好起来了，awesome，就很离谱。
![image](https://user-images.githubusercontent.com/28354069/139441058-9be59232-fb35-4507-b7dc-8f9720fbd7b1.png)

**Comment by usagiring** [comment]
端口被占用了，现在是默认使用8081端口，以后我想想优化下报错做成可配置吧
