### ISSUE TITLE
关于可能的未来

### ISSUE THREAD

**Issue by Zawinzala** [hling51325/bilibili-live-danmaku#23]
我很喜欢这个软件，作者很棒，更新很勤快，所以。

我可以提供一些可能的方向?

比如，解决高频弹幕下主播的痛点，写好了感觉非常实用，而且
而且没有竞品，推广开应该很容易。
嘿嘿。

感觉会受到很多大主播的青睐，我这种小主播就没啥需要了QaQ

![演示图片1](https://user-images.githubusercontent.com/24386549/145902704-23c4c171-cd68-456d-87f0-e2c1cadf2704.png)

**Comment by Zawinzala** [comment]
焦点话题可以从词云快速聚焦，
焦点用户可以从右侧弹幕滚动表快速聚焦。
所有内容均保存到json文件存在文档里面。焦点菜单栏可以打开历史焦点。

**Comment by usagiring** [comment]
过奖了，感谢反馈，都是挺好的建议。
设置关键词/焦点我应该会做进去。关注人列表因为B站有关注人隐私设置，我这边应该会做成配置用户id。
因为某种规则高亮一些信息，表现上虽然有差异，本质上可能和舰长弹幕差不多。
人工智能类的做不了，应该会和设置规则类似，一是我不会写，二是纯客户端应用可利用的数据有限。

最近我打算优化一版统计，词云等等也考虑加进去。我先把统计和数据导出做完，然后再看看能不能做到实时信息提炼。

**Comment by Zawinzala** [comment]
期待。

**Comment by Zawinzala** [comment]
哈哈哈哈看到词云了哈哈哈哈哈哈。

**Comment by Zawinzala** [comment]
挺有用的而且挺萌的hhhhhh
